/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        display: ['"Barlow Condensed"', 'Inter', 'sans-serif'],
        condensed: ['"Barlow Condensed"', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'xs': ['0.7rem', { lineHeight: '0.95rem' }],
        'sm': ['0.82rem', { lineHeight: '1.15rem' }],
        'base': ['0.9375rem', { lineHeight: '1.5rem' }],
        'lg': ['1.0625rem', { lineHeight: '1.6rem' }],
        'xl': ['1.1875rem', { lineHeight: '1.7rem' }],
        '2xl': ['1.4375rem', { lineHeight: '1.95rem' }],
        '3xl': ['1.8125rem', { lineHeight: '2.2rem' }],
        '4xl': ['2.125rem', { lineHeight: '2.45rem' }],
        '5xl': ['2.8125rem', { lineHeight: '3.05rem' }],
        '6xl': ['3.5rem', { lineHeight: '3.6rem' }],
        '7xl': ['4.1875rem', { lineHeight: '4.2rem' }],
        '8xl': ['5.5rem', { lineHeight: '5.5rem' }],
        '9xl': ['7.25rem', { lineHeight: '7.25rem' }],
      },
      spacing: {
        'px': '1px',
        '0': '0px',
        '0.5': '0.1rem',
        '1': '0.2rem',
        '1.5': '0.3rem',
        '2': '0.4rem',
        '2.5': '0.5rem',
        '3': '0.6rem',
        '3.5': '0.7rem',
        '4': '0.85rem',
        '5': '1rem',
        '6': '1.2rem',
        '7': '1.4rem',
        '8': '1.7rem',
        '9': '1.9rem',
        '10': '2.1rem',
        '11': '2.35rem',
        '12': '2.55rem',
        '14': '3rem',
        '16': '3.4rem',
        '20': '4.25rem',
        '24': '5.1rem',
        '28': '5.95rem',
        '32': '6.8rem',
        '36': '7.65rem',
        '40': '8.5rem',
        '44': '9.35rem',
        '48': '10.2rem',
        '52': '11.05rem',
        '56': '11.9rem',
        '60': '12.75rem',
        '64': '13.6rem',
        '72': '15.3rem',
        '80': '17rem',
        '96': '20.4rem',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.96)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        marquee: 'marquee 25s linear infinite',
        'fade-in': 'fade-in 200ms ease-out both',
        'scale-in': 'scale-in 200ms ease-out both',
      },
    },
  },
  plugins: [],
};
